### ISSUE TITLE
ActiveMQ Out of Memory error in 2G limit container

### ISSUE THREAD

**Issue by vnugent** [hawkular/hawkular-services#101]
Container is given 2G memory limit.
Environment: OpenShift Origin v1.3.1

How to reproduce:
```
oc create -f all-in-one-template.yaml
oc new-app -t hawkular-full
```

[all-in-one-template.yaml.txt](https://github.com/hawkular/hawkular-services/files/607095/all-in-one-template.yaml.txt)

[hawkular-oom.log.txt](https://github.com/hawkular/hawkular-services/files/607102/hawkular-oom.log.txt)

**Comment by pilhuhn** [comment]
What version of services is that? And with what datastore?

**Comment by vnugent** [comment]
0.23.0.Final-SNAPSHOT (commit 4250d21589cf10596ad4fad77cae54ca5a0468a0) with separate C*node container

Still a problem after MEM limit was raised to 4G
```
# docker stats e121042fb7af 
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O
e0c25e9b4143        0.53%               1.289 GB / 4.295 GB   30.01%              26.99 kB / 28.87 kB   486.4 kB / 28.89 MB
```
I'm having VPN issue so don't  have access to OpenShift Enterprise 3 to confirm.

**Comment by pgier** [comment]
This looks like the same issue I've seen before using a Fedora 24 host.
https://issues.jboss.org/browse/HAWKULAR-1131
I didn't see the issue when using the same container on a RHEL 7 or Fedora 23 host.

**Comment by vnugent** [comment]
I can confirm that it's *not* a problem on OSE 3.2/RHEL 7.2 node

OSE v3.2 node
- docker-common-1.10.3-44.el7.x86_64
- RHEL 7.2

Origin node
-  v1.3 docker-common-1.10.3-54.gite03ddb8.fc24.x86_64
- Fedora 24
