### ISSUE TITLE
Exposing all tenants name to users

### ISSUE THREAD

**Issue by adrianlzt** [hawkular/hawkular-services#168]
I have an installation of OpenShift with Hawkular configured.
Just realized that any user could ask Hawkular to list which tenants are available and obtain the list of available projects (not just his project). This leaking of info does not seem appropriate.

**Comment by jotak** [comment]
Which version are you using? The /tenants endpoint is admin-protected for a while now, cf https://issues.jboss.org/browse/HWKMETRICS-478

**Comment by adrianlzt** [comment]
OpenShift 3.5.0. Probably and old version of Hawkular.
Thanks

**Comment by jotak** [comment]
Actually, I'm surprised that users can see all tenants in OS 3.5.
Is it through the /tenants endpoint, or in a different way?

**Comment by jotak** [comment]
@mwringe any idea about it?

**Comment by adrianlzt** [comment]
This is what I have executed:
```
$ curl -H "Hawkular-Tenant: MYPROJECT" -H "Authorization: Bearer xxxxxxxxxxx" https://hawkular-metrics.apps.xxx.com/hawkular/metrics/tenants
[{"id":"AAA"},{"id":"BBB"},{"id":"CCC"},{"id":"network-diag-global-ns-3z7v5"},{"id":"DDD"},{"id":"openshift-infra"},{"id":"_hawkular_admin"},{"id":"network-diag-ns-vpj5d"},{"id":"_system"},{"id":"logging"},{"id":"network-diag-ns-3vrkr"},{"id":"EEE"},{"id":"network-diag-global-ns-6bmt8"},{"id":"FFF"}]
```

Don't discard some error in my side, I'm quite new using openshift.

**Comment by jotak** [comment]
Ok, then I expect this call to work if and only if the provided authorization token is an admin one. Using some user, non-admin token here should result in a 'forbidden' answer.
Which means that this token/query should obviously not to be shared to other users.

**Comment by adrianlzt** [comment]
Then token come from my user account.
