### ISSUE TITLE
Hawkular Agent unable to connect to hawkular services on Openshift

### ISSUE THREAD

**Issue by gbaufake** [hawkular/hawkular-services#172]
I created a hawkular services instance on Openshift using a "standard" configuration (https://github.com/hawkular/hawkular-services/blob/master/openshift/hawkular-services-ephemeral.yaml)

It appears the Hawkular Agent is not starting on the Openshift 

`21:19:03,610 INFO  [org.hawkular.agent.monitor.service.AgentCoreEngine] (Hawkular Java Agent Start Thread) HAWKMONITOR010000: Starting Hawkular Agent`

`21:19:29,461 INFO  [org.hawkular.agent.monitor.cmd.FeedCommProcessor] (Hawkular Java Agent Start Thread) HAWKMONITOR010039: The command-gateway URL is [wss://127.0.0.1:8443/hawkular/command-gateway/feed/hawkular-services-2-sh9vg]`

` 21:19:29,503 INFO  [org.hawkular.agent.monitor.scheduler.SchedulerService] (Hawkular Java Agent Start Thread) HAWKMONITOR010012: Starting scheduler`

`21:19:29,512 INFO  [org.hawkular.agent.monitor.protocol.ProtocolServices] (Hawkular Java Agent Start Thread) HAWKMONITOR010019: Managed server [Local DMR] is disabled. It will not be monitored `

`21:19:29,571 INFO  [org.hawkular.agent.monitor.cmd.FeedCommProcessor] (OkHttp https://127.0.0.1:8443/...) HAWKMONITOR010034: Opened feed WebSocket connection to endpoint [wss://127.0.0.1:8443/hawkular/command-gateway/feed/hawkular-services-2-sh9vg]`

`21:19:30,555 INFO  [org.hawkular.agent.monitor.protocol.EndpointService] (Hawkular Java Agent Start Thread) Endpoint [DMREndpointService[Endpoint[Local]:[https-remoting://127.0.0.1:9993]]] is not ready yet - will wait`

[Full Log](https://paste.fedoraproject.org/paste/-WMtDG17pEcxwZnIcgWDGg)

I am using standard username/password (`username=jdoe` and `password=password`).

I talked with @josejulio and @jmazzitelli, it seems to be ok docker container and it is more related to openshift.

Best Regards,
Guilherme Baufaker Rêgo

**Comment by josejulio** [comment]
It appears that we need to also add the username/password to management realm when running this container on openshift. Will work on a PR that does that. Thanks!
