### ISSUE TITLE
Admin-Token for metrics isn't set on docker image

### ISSUE THREAD

**Issue by garethahealy** [hawkular/hawkular-services#77]
The latest metrics introduces "-Dhawkular.metrics.admin-token". As its not on the base docker image, any calls to /tenants fail.

https://github.com/hawkular/hawkular-metrics/blob/b5e1a337e206c961c3b9e8b47d40e28d081c2c59/api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/AdminFilter.java#L67

https://github.com/hawkular/hawkular-services/blob/master/docker-dist/src/main/resources/startcmd.sh

**Comment by pilhuhn** [comment]
What is the use case / need for this?

**Comment by garethahealy** [comment]
As per the comment on the PR, i dont think its needed anymore. I didn't realise you could use the ADMIN_TOKEN env var before raising the PR.

Happy to close if you dont think its needed as well.
